# Generated by Django 6.0.3 on 2026-03-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_image_url_project_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
    ]
