# Generated by Django 6.0.3 on 2026-04-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(max_length=500),
        ),
    ]
