# Generated by Django 6.0.3 on 2026-04-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
